<a href="https://colab.research.google.com/github/filipoky/my_hw_ds_projects/blob/main/Hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np

# 1. Одновимірний масив з перших 10 натуральних чисел
a1 = np.arange(1, 11)
print(a1)

[ 1  2  3  4  5  6  7  8  9 10]


In [8]:
# 2. Двовимірна матриця 3x3 з нулями
a2 = np.zeros((3, 3))
print(a2)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
# 3. Матриця 5x5 з випадковими цілими від 1 до 10
a3 = np.random.randint(1, 11, size=(5, 5))
print(a3)

[[ 8  1  7  2  1]
 [ 6  5  2  8  1]
 [10  6  4  7  2]
 [ 9  4  1  5  7]
 [ 7  2  5 10  3]]


In [10]:
# 4. Матриця 4x4 з випадковими дійсними числами від 0 до 1
a4 = np.random.random((4, 4))
print(a4)


[[0.25185055 0.10031546 0.32600307 0.93157195]
 [0.67964581 0.62894556 0.89756962 0.16132537]
 [0.8984542  0.92271671 0.91222941 0.07607197]
 [0.61161754 0.79508123 0.99214268 0.93127448]]


In [12]:
# 5. Два вектори, поелементні операції
v1 = np.random.randint(1, 11, size=5)
v2 = np.random.randint(1, 11, size=5)
print("Вектори:", v1, v2)
print("Додавання:", v1 + v2)
print("Віднімання:", v1 - v2)
print("Множення:", v1 * v2)


Вектори: [4 1 1 8 8] [1 2 3 4 3]
Додавання: [ 5  3  4 12 11]
Віднімання: [ 3 -1 -2  4  5]
Множення: [ 4  2  3 32 24]


In [14]:
# 6. Скалярний добуток векторів розміром 7
v3 = np.random.random(7)
v4 = np.random.random(7)
dot_product = np.dot(v3, v4)
print(v3)
print(v4)
print(dot_product)

[0.71369076 0.81530132 0.37679276 0.62265522 0.94128741 0.06112001
 0.81762449]
[0.42521155 0.78387184 0.03844721 0.53209624 0.14179318 0.10617827
 0.56101252]
1.8870157599311177


In [22]:
# 7. Множення 2x2 і 2x3
m1 = np.random.randint(1, 11, size=(2, 2))
m2 = np.random.randint(1, 11, size=(2, 3))
m_mult = np.dot(m1, m2)
print("Матриці:\n", m1, "\n", m2)
print("Добуток:\n", m_mult)

Матриці:
 [[9 7]
 [2 4]] 
 [[ 9  1  6]
 [10  7  9]]
Добуток:
 [[151  58 117]
 [ 58  30  48]]


In [21]:
# 8. Обернена матриця 3x3
m3 = np.random.randint(1, 11, size=(3, 3))
m3_inv = np.linalg.inv(m3)
print("Матриця:\n", m3)
print("Обернена:\n", m3_inv)

Матриця:
 [[6 4 2]
 [7 9 4]
 [4 7 2]]
Обернена:
 [[ 0.38461538 -0.23076923  0.07692308]
 [-0.07692308 -0.15384615  0.38461538]
 [-0.5         1.         -1.        ]]


In [23]:
# 9. Транспонована матриця 4x4
m4 = np.random.random((4, 4))
print("Матриця:\n", m4)
print("Транспонована:\n", m4.T)

Матриця:
 [[0.45250351 0.80673493 0.5363847  0.4218076 ]
 [0.35773566 0.72883853 0.08311354 0.27639752]
 [0.86688175 0.81594069 0.47078907 0.60602288]
 [0.08357617 0.77746731 0.29857111 0.25675801]]
Транспонована:
 [[0.45250351 0.35773566 0.86688175 0.08357617]
 [0.80673493 0.72883853 0.81594069 0.77746731]
 [0.5363847  0.08311354 0.47078907 0.29857111]
 [0.4218076  0.27639752 0.60602288 0.25675801]]


In [24]:
# 10. Матриця 3x4 * вектор 4
m5 = np.random.randint(1, 11, size=(3, 4))
v5 = np.random.randint(1, 11, size=4)
mv_mult = np.dot(m5, v5)
print("Матриця:\n", m5)
print("Вектор:", v5)
print("Добуток:", mv_mult)

Матриця:
 [[ 1  8  9  3]
 [ 6  9  5  7]
 [10  3 10  7]]
Вектор: [10  1  1  3]
Добуток: [ 36  95 134]


In [25]:
# 11. Матриця 2x3 * вектор 3
m6 = np.random.random((2, 3))
v6 = np.random.random(3)
mv_mult2 = np.dot(m6, v6)
print("Матриця:\n", m6)
print("Вектор:", v6)
print("Добуток:", mv_mult2)

Матриця:
 [[0.466978   0.41828813 0.41691476]
 [0.78495957 0.09960048 0.53239233]]
Вектор: [0.93928884 0.95130431 0.5451999 ]
Добуток: [1.06384841 1.12231437]


In [29]:
# 12. Поелементне множення 2x2
m7 = np.random.randint(1, 11, size=(2, 2))
m8 = np.random.randint(1, 11, size=(2, 2))
elem_mult = m7 * m8
print("Матриця1:\n", m7)
print("Матриця2:\n", m8)
print("Поелементне множення:\n", elem_mult)

Матриця1:
 [[ 3 10]
 [ 3  4]]
Матриця2:
 [[1 3]
 [9 6]]
Поелементне множення:
 [[ 3 30]
 [27 24]]


In [30]:
# 13. Добуток матриць 2x2
m9 = np.random.randint(1, 11, size=(2, 2))
m10 = np.random.randint(1, 11, size=(2, 2))
mat_mult = np.dot(m9, m10)
print("Матриця1:\n", m9)
print("Матриця2:\n", m10)
print("Добуток матриць:\n", mat_mult)

Матриця1:
 [[10  2]
 [ 2  4]]
Матриця2:
 [[ 7 10]
 [ 7  4]]
Добуток матриць:
 [[ 84 108]
 [ 42  36]]


In [34]:
# 14. Сума елементів матриці 5x5
m11 = np.random.randint(1, 101, size=(5, 5))
sum_m11 = np.sum(m11)
print("Матриця:\n",m11)
print("Сума елементів 5x5:", sum_m11)

Матриця:
 [[43 91 24 25 99]
 [57 61 74 70 85]
 [15 57 86 79  7]
 [89 99 29 61 58]
 [67 82 13 52 26]]
Сума елементів 5x5: 1449


In [35]:
# 15. Різниця двох матриць 4x4
m12 = np.random.randint(1, 11, size=(4, 4))
m13 = np.random.randint(1, 11, size=(4, 4))
diff = m12 - m13
print("Матриця1:\n", m12)
print("Матриця2:\n", m13)
print("Різниця:\n", diff)

Матриця1:
 [[5 7 6 3]
 [2 4 4 4]
 [3 1 6 8]
 [8 5 6 9]]
Матриця2:
 [[ 4  5  2  6]
 [ 8 10  3  4]
 [ 1  6  4  3]
 [ 3 10  2  5]]
Різниця:
 [[ 1  2  4 -3]
 [-6 -6  1  0]
 [ 2 -5  2  5]
 [ 5 -5  4  4]]


In [36]:
# 16. Сума по рядках 3x3
m14 = np.random.random((3, 3))
row_sums = np.sum(m14, axis=1)
print("Матриця:\n", m14)
print("Сума по рядках:", row_sums)

Матриця:
 [[0.14855088 0.19907668 0.31176779]
 [0.77410681 0.79875395 0.49593046]
 [0.6174636  0.40519044 0.03352362]]
Сума по рядках: [0.65939534 2.06879122 1.05617766]


In [37]:
# 17. Квадрати чисел матриці 3x4
m15 = np.random.randint(1, 11, size=(3, 4))
m15_squared = m15 ** 2
print("Матриця:\n", m15)
print("Квадрати:\n", m15_squared)

Матриця:
 [[ 4  5 10  1]
 [ 9  1  2  4]
 [10  3  4  3]]
Квадрати:
 [[ 16  25 100   1]
 [ 81   1   4  16]
 [100   9  16   9]]


In [38]:
# 18. Квадратні корені вектора розміром 4
v7 = np.random.randint(1, 51, size=4)
v7_sqrt = np.sqrt(v7)
print("Вектор:", v7)
print("Квадратні корені:", v7_sqrt)

Вектор: [17 22  4  3]
Квадратні корені: [4.12310563 4.69041576 2.         1.73205081]
