<a href="https://colab.research.google.com/github/filipoky/my_hw_ds_projects/blob/main/Hw1a.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# 1. Заміна усіх непарних чисел на -1
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [2]:
# 2. Створіть та перетворіть 1D-масив на 2D-масив із 2 рядками
arr = np.arange(10)
arr_2d = arr.reshape(2, -1)
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [3]:
# 3. Створіть два 2D масиви і складіть їх вертикально
a = np.arange(4).reshape(2,2)
b = np.arange(4,8).reshape(2,2)
v_stack = np.vstack((a,b))
print(v_stack)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [4]:
# 4. Створіть шаблон без Hard coding
a = np.array([1,2,3])
out = np.r_[np.repeat(a, 3), np.tile(a, 3)]
print(out)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [5]:
# 5. Отримайте спільні елементи між a і b
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
common = np.intersect1d(a,b)
print(common)

[2 4]


In [6]:
# 6. Позиції перших 5 максимальних значень
np.random.seed(100)
a = np.random.uniform(1,50, 20)
ind = np.argsort(a)[-5:][::-1]
print(ind)

[15 10  3  7 18]


In [7]:
# 7. Вилучіть NaN
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
a_nonan = a[~np.isnan(a)]
print(a_nonan)

[1. 2. 3. 5. 6. 7.]


In [8]:
# 8. Евклідова відстань
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
dist = np.linalg.norm(a - b)
print(dist)

6.708203932499369


In [9]:
# 9. Індекс 5-го повторення числа 1
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
idx = np.where(x == 1)[0][4]
print(idx)

8


In [11]:
# 10. Знайдіть повтори (з 2-го і далі)
np.random.seed(100)
a = np.random.randint(0, 5, 10)
print("Input a:", a)

uniq, idx, counts = np.unique(a, return_index=True, return_counts=True)
out = np.zeros_like(a, dtype=bool)

# працюємо з унікальними значеннями
for i in uniq[counts > 1]:
    inds = np.where(a == i)[0]
    out[inds[1:]] = True

print(out)


Input a: [0 0 3 0 2 4 2 2 2 2]
[False  True False  True False False  True  True  True  True]
